config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  get 'welcome/index'

  # get 'signup', to: 'users#new', as: 
  # get 'logout', to: 'sessions#destroy', as: 'l'signup'
  # get 'login', to: 'sessions#new', as: 'login'ogout'
  get :logged_in, to: 'sessions#logged_in'
  delete :logout, to: 'sessions#logout'

  resources :users
  resources :registrations, only: :create
  resources :sessions, only: [:new, :create, :destory]
  
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"

  skip_before_action :verify_authenticity_token
  
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else 
      @current_user = nil
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: 'secret', except: [:index, :show]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    if @article.nil?
      render action: 'index'
    end
  end

  def new 
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
    render 'edit'
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    redirect_to articles_path
  end

  private def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(@article)
  end

  private def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  included do
    before_action :set_current_user
  end
  
  def set_current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def create
    user = User.create!(
      email: params["user"]["email"],
      password: params["user"]["password"],
      password_confirmation: params["user"]["password_confirmation"]
    )

    if user
      session[:user_id] = user.id
      render json: {
        status: :created,
        user: user
      }
    else
      render json: { status: 500 }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include CurrentUserConcern

  def new
  end

  def create
    # use rails views
    # user = User.find_by_email(params[:email])
    
    # if user && user.authenticate(params[:password])
    #   session[:user_id] = user.id
    #   redirect_to root_url, notice: "Logged in!"
    # else
    #   flash.now[:alert] = "Email or password is invalid!"
    #   render "new"
    # end

    # use frontend app
    user = User
            .find_by(email: params["user"]["email"])
            .try(:authenticate, params["user"]["password"])
    if user
      session[:user_id] = user.id
      render json: {
        status: :created,
        logged_in: true,
        user: user
      }
    else
      render json: { status: 401 }
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

  def logged_in
    if @current_user
      render json: {
        logged_in: true,
        user: @current_user
      }
    else
      render json: {
        logged_in: false
      }
    end
  end

  def logout
    reset_session
    render json: { status: 200, logged_out:true }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render json: { status: "It works!"} # comment this line if you want to use views
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <% if @article.errors.any? %>
    <div class="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> 
        prohibited this article from being save:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :text %><br>
    <%= form.text_area :text, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Edit Article</h1>
  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1>Listing Articles</h1>

  <%= link_to 'My Blog', { controller => 'articles'}, class: "btn btn-secondary" %>
  <%= link_to 'New article', new_article_path, class: "btn btn-primary ml-1" %>
  
  <table class="table table-bordered mt-2">
    <tr>
      <th class="text-center">Title</th>
      <th class="text-center">Text</th>
      <th class="text-center">Actions</th>
    </tr>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td class="text-center">
          <%= link_to 'Show', article_path(article) %>
          <%= link_to 'Edit', edit_article_path(article) %>
          <%= link_to 'Delete', 
                        article_path(article), 
                        method: :delete, 
                        data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>New Article</h1>

  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @article.title %></h5>
      <P class="card-text">
        <%= @article.text %>
      </p>
    </div>
  </div>

  <h2>Comments</h2>
  <%= render @article.comments %>

  <h2>Add a comment: </h2>
  <%= render 'comments/form' %>

  <%= link_to 'Back', articles_path %>
  <%= link_to 'Edit', edit_article_path(@article) %>
</div>

app/views/comments/_comment.html.erb
<div class="alert alert-dark">
  <p>
    <strong>Comment: </strong>
    <%= comment.body %>    
  </p>
  
  <p class="text-muted">
    <strong>by </strong>
    <%= comment.commenter %>    
  </p>

  <%= link_to 'Delete', 
    [
      comment.article,
      comment
    ], 
    method: :delete,
    data: { confirm: 'Are you sure?' } %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [
  @article,
  @article.comments.build
], local: true) do |form| %>
  <div>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </div>

  <%= form.submit %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-5">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="#">Rails Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>New User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <h1>Hello, Rails</h1>

  <% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to "Log Out", logout_path %>
  <% else %>
    <%= link_to "Sign Up", signup_path %> | 
    <%= link_to "Log in", login_path %>
  <% end %>

  <p id="notice"><%= notice %></p>
</div>